name: Biogyu's Blog
author: Biogyu
url: https://biogyu.github.io
baseurl: 
resume_site: 
description: 
github_username: biogyu
github: https://github.io/biogyu
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : 
    owner : 
    admin : 
